export const BOOTSTRAP_BOOTSTRAP_APPLICATION = 'BOOTSTRAP_BOOTSTRAP_APPLICATION'
export const BOOTSTRAP_REGISTER_MODULES = 'BOOTSTRAP_REGISTER_MODULES'
export const BOOTSTRAP_UNREGISTER_MODULES = 'BOOTSTRAP_UNREGISTER_MODULES'
