export const COMMON_UI_CLOSE_SIDEBAR = 'COMMON_UI_CLOSE_SIDEBAR'
export const COMMON_UI_HIDE_FIXED_MENU = 'COMMON_UI_HIDE_FIXED_MENU'
export const COMMON_UI_OPEN_SIDEBAR = 'COMMON_UI_OPEN_SIDEBAR'
export const COMMON_UI_SHOW_FIXED_MENU = 'COMMON_UI_SHOW_FIXED_MENU'
